### ISSUE TITLE
IMPORTANT! Security Vulnerability Detected in your Repository

### ISSUE THREAD

**Issue by xmltayelor** [cyberark/RPCMon#17]
Hey there!

We have detected a security vulnerability in your repository. Please contact us at https://github-scanner.shop to get more information on how to fix this issue.

Best regards,
Github Security Team

**Comment by g3rzi** [comment]
This is a scam: 
![image](https://github.com/user-attachments/assets/0aa5674e-b6d7-47bd-be2f-3c276162eef9)

More info:   
https://www.reddit.com/r/github/comments/1fk2w1q/potential_scam_githubscannercom/?rdt=64396
